---

.script-git-submodule: &script-git-submodule
  - |
    git submodule sync --recursive
    git submodule update --init --recursive

.script-bootstrap-packer: &script-bootstrap-packer
  - |
    curl -skL -O https://releases.hashicorp.com/packer/1.6.6/packer_1.6.6_linux_amd64.zip
    sudo unzip -qq -o -d /usr/local/bin packer_1.6.6_linux_amd64.zip
    rm -rf packer_1.6.6_linux_amd64.zip

.script-bootstrap-docker: &script-bootstrap-docker
  - |
    curl -skL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update
    sudo apt-get -y install containerd.io docker-ce docker-ce-cli
    sudo systemctl start docker.service

.script-bootstrap-ansible: &script-bootstrap-ansible
  - |
    sudo apt-get update
    sudo apt-get -y install ca-certificates curl gcc iproute2 pwgen python3 python3-dev sudo
    curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3 - --prefix=/usr/local
    sudo -H pip3 install --prefix=/usr/local --upgrade --requirement requirements.txt

.script-linters: &script-linters
  - |
    yamllint .
    ansible-lint
    flake8

.script-packer-build: &script-packer-build
  - |
    cd $CI_PROJECT_DIR/packer/$_PACKER_BUILDER_PROVIDER-$_PACKER_BUILDER_VERSION
    export _ORG=$CI_PROJECT_NAMESPACE
    export _IMAGE=$(echo $CI_PROJECT_NAME | sed 's/^docker-//g')-$_PACKER_BUILDER_VERSION
    sudo packer build packer.json
    export _ID=$(sudo docker images | awk '{print $3}' | awk 'NR==2')
    mkdir -p output-docker
    sudo docker tag $_ID $_ORG/$_IMAGE:latest
    sudo docker save $_ORG/$_IMAGE:latest | gzip -9 > output-docker/image.tar.gz

.script-docker-run: &script-docker-run
  - |
    cd $CI_PROJECT_DIR/packer/$_PACKER_BUILDER_PROVIDER-$_PACKER_BUILDER_VERSION
    export _ORG=$CI_PROJECT_NAMESPACE
    export _IMAGE=$(echo $CI_PROJECT_NAME | sed 's/^docker-//g')-$_PACKER_BUILDER_VERSION
    sudo docker load --input output-docker/image.tar.gz
    sudo docker run -itd $_ORG/$_IMAGE:latest

.script-docker-push: &script-docker-push
  - |
    cd $CI_PROJECT_DIR/packer/$_PACKER_BUILDER_PROVIDER-$_PACKER_BUILDER_VERSION
    export _ORG=$CI_PROJECT_NAMESPACE
    export _IMAGE=$(echo $CI_PROJECT_NAME | sed 's/^docker-//g')-$_PACKER_BUILDER_VERSION
    if [[ -n "$CI_COMMIT_TAG" ]] && [[ "$CI_COMMIT_TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
      export _TAG=$CI_COMMIT_TAG
    elif [[ -n "$CI_COMMIT_BRANCH" ]] && [[ "$CI_COMMIT_BRANCH" =~ master ]]; then
      export _TAG=$(date +%Y%m%d).0.0
    else
      exit 0
    fi
    echo $DOCKER_HUB_TOKEN | sudo docker login --username=$DOCKER_HUB_USERNAME --password-stdin
    sudo docker load --input output-docker/image.tar.gz
    sudo docker push $_ORG/$_IMAGE:latest
    sudo docker tag $_ORG/$_IMAGE:latest $_ORG/$_IMAGE:$_TAG
    sudo docker push $_ORG/$_IMAGE:$_TAG

.job-packer-build: &job-packer-build
  cache:
    paths:
      - packer/*/output-docker/*.tar.gz
  script:
    - *script-bootstrap-packer
    - *script-bootstrap-docker
    - *script-bootstrap-ansible
    - *script-linters
    - *script-packer-build

.job-docker-run: &job-docker-run
  cache:
    paths:
      - packer/*/output-docker/*.tar.gz
    policy: pull
  script:
    - *script-bootstrap-docker
    - *script-docker-run

.job-docker-push: &job-docker-push
  cache:
    paths:
      - packer/*/output-docker/*.tar.gz
    policy: pull
  script:
    - *script-bootstrap-docker
    - *script-docker-push

default:
  before_script:
    - *script-git-submodule

build:docker-10.5:
  <<: *job-packer-build
  stage: build
  cache:
    key: "$CI_PIPELINE_ID-docker-10.5"
  variables:
    _PACKER_BUILDER_PROVIDER: "docker"
    _PACKER_BUILDER_VERSION: "10.5"

test:docker-10.5:
  <<: *job-docker-run
  stage: test
  cache:
    key: "$CI_PIPELINE_ID-docker-10.5"
  variables:
    _PACKER_BUILDER_PROVIDER: "docker"
    _PACKER_BUILDER_VERSION: "10.5"
  needs:
    - build:docker-10.5

deploy:docker-10.5:
  <<: *job-docker-push
  stage: deploy
  cache:
    key: "$CI_PIPELINE_ID-docker-10.5"
  variables:
    _PACKER_BUILDER_PROVIDER: "docker"
    _PACKER_BUILDER_VERSION: "10.5"
  needs:
    - test:docker-10.5

build:docker-10.4:
  <<: *job-packer-build
  stage: build
  cache:
    key: "$CI_PIPELINE_ID-docker-10.4"
  variables:
    _PACKER_BUILDER_PROVIDER: "docker"
    _PACKER_BUILDER_VERSION: "10.4"

test:docker-10.4:
  <<: *job-docker-run
  stage: test
  cache:
    key: "$CI_PIPELINE_ID-docker-10.4"
  variables:
    _PACKER_BUILDER_PROVIDER: "docker"
    _PACKER_BUILDER_VERSION: "10.4"
  needs:
    - build:docker-10.4

deploy:docker-10.4:
  <<: *job-docker-push
  stage: deploy
  cache:
    key: "$CI_PIPELINE_ID-docker-10.4"
  variables:
    _PACKER_BUILDER_PROVIDER: "docker"
    _PACKER_BUILDER_VERSION: "10.4"
  needs:
    - test:docker-10.4

build:docker-10.3:
  <<: *job-packer-build
  stage: build
  cache:
    key: "$CI_PIPELINE_ID-docker-10.3"
  variables:
    _PACKER_BUILDER_PROVIDER: "docker"
    _PACKER_BUILDER_VERSION: "10.3"

test:docker-10.3:
  <<: *job-docker-run
  stage: test
  cache:
    key: "$CI_PIPELINE_ID-docker-10.3"
  variables:
    _PACKER_BUILDER_PROVIDER: "docker"
    _PACKER_BUILDER_VERSION: "10.3"
  needs:
    - build:docker-10.3

deploy:docker-10.3:
  <<: *job-docker-push
  stage: deploy
  cache:
    key: "$CI_PIPELINE_ID-docker-10.3"
  variables:
    _PACKER_BUILDER_PROVIDER: "docker"
    _PACKER_BUILDER_VERSION: "10.3"
  needs:
    - test:docker-10.3
