---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-mysql-mariadb-conf-d
data:
  mysqld.cnf: |
    [mysqld]
    binlog_format = row
    character_set_server = utf8mb4
    collation_server = utf8mb4_general_ci
    default_storage_engine = InnoDB
    innodb_autoinc_lock_mode = 2
    innodb_buffer_pool_size = 128M
    innodb_flush_log_at_trx_commit = 2
    key_buffer_size = 32M
    max_allowed_packet = 128M
    max_connections = 128
    query_cache_limit = 8M
    sql_mode = NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    table_open_cache = 512
